org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# NeoForge / Minecraft 26.1.2
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109
neo_version_range=[26.1.2.109,]
loader_version_range=[4,)

# Oritech dependency
oritech_version=2.0.0-exp6
oritech_version_range=[2.0.0,]
oritech_curseforge_file=8780393

# Compatible libraries
geckolib_version=5.5.1
jei_version=29.20.0.53

# Addon properties
mod_id=oritechthings
mod_name=Oritech Things
mod_license=CC4.0
mod_version=0.1.2
mod_group_id=com.lumengrid.oritechthings
mod_authors=Lumengrid,muroalparco,MtcLeo05,DevDyna,Sirios_dev
mod_description=Some additional things for Oritech mod.
